---

  - name: DB Servers Insall
    become: yes
    hosts: db
    tasks:

      - name: Install MariaDB and Galera
        ansible.builtin.package:
            name:
              - mariadb-server
              - mariadb-client
              - galera-3
            state: present

      - name: Install my.cnf file
        ansible.builtin.copy:
            src: templates/db/my.cnf
            dest: /etc/mysql/mariadb.cnf
            owner: root
            group: root
            mode: "0644"

      - name: Create override directory
        ansible.builtin.file:
            path: /etc/systemd/system/mysql.service.d
            state: directory

      - name: Override values for mysqld.service
        ansible.builtin.copy:
            src: templates/db/override.conf
            dest: /etc/systemd/system/mysql.service.d/override.conf

      - name: Ensure mysqld is running (note, may need to bootstrap)
        ansible.builtin.service:
            name: mysqld
            state: restarted
