---

  - name: DB Servers Insall
    become: yes
    hosts: db
    tasks:

      - name: Install MariaDB
        ansible.builtin.package:
            name: mariadb-server
            state: present


